constants:
    !include config/constants.yaml

working_directory: /mnt/tamborgmatic/merged
source_directories: ["."]
source_directories_must_exist: true
numeric_ids: true
one_file_system: false
read_special: false     # Uses "specialfile" to selectively read.
exclude_caches: true
keep_exclude_tags: true
store_config_files: false

exclude_patterns:
    - fm:*.py[cod]
    # fm:*/node_modules/ not excluded, as not all of them were created with "npm install"

    - fm:*/.gradle/
    # Attempt to exclude Android Studio build/ but nothing else:
    - fm:*/app/build/intermediates/
    - fm:*/app/build/outputs/
    - fm:*/app/build/kotlin/
    - fm:*/app/build/tmp/
    - fm:*/app/build/generated/

    # Note: the following assumes "linux_root" name is used in bupsrcs.cfg
    # (and that /home/ is in the same partition as /)

    - pf:linux_root/swapfile
    - pf:linux_root/swap.img
    - pf:linux_root/tmp
    - pf:linux_root/var/cache/apt
    - pf:linux_root/var/tmp
    # cdrom, dev, media, mnt, proc, run and sys: only the empty dirs will be stored.

    - sh:linux_root/home/*/.android/build-cache
    - sh:linux_root/home/*/.ansible/tmp
    - sh:linux_root/home/*/.cache
    - sh:linux_root/home/*/.cinnamon/spices.cache
    - sh:linux_root/home/*/.config/*/*Cache*  # crappy Electron apps which don't use .cache/
    - sh:linux_root/home/*/.config/chromium/*/GPUCache
    - sh:linux_root/home/*/.config/chromium/*/Service Worker/CacheStorage
    - sh:linux_root/home/*/.gvfs
    - sh:linux_root/home/*/.ICEauthority
    - sh:linux_root/home/*/.local/share/virtualenvs
    - sh:linux_root/home/*/.mozilla/firefox/Crash Reports
    - sh:linux_root/home/*/.mozilla/firefox/*/datareporting
    - sh:linux_root/home/*/.npm/_cacache
    - sh:linux_root/home/*/.local/share/TelegramDesktop/tdata/*/*cache*
    - sh:linux_root/home/*/.Xauthority
    - pf:linux_root/root/.cache

verbosity: 1
encryption_passphrase: "{encryption_passphrase}"
compression: zstd,3
repositories:
    - path: ssh://borg@{server_ip}/./TAM
borg_base_directory: "{home}"
default_actions: false

# Backup to a temporary archive first, and rename it to a full name only if successful.
# Otherwise, archives kept by prune could be ones with errors!
archive_name_format: "{server_user}[temp]"

# Use HPN SSH with some options, as the original user if sudo was used.
#   sh makes env vars work.
#   SSH_AUTH_SOCK provides unlocked identity_file.
#   As Borg appends parameters to the command, and -c requires quotes, $@ is used. "0" fills $0.
ssh_command: sh -c 'sudo -u "${SUDO_USER:-$USER}" SSH_AUTH_SOCK="$SSH_AUTH_SOCK" /bin/hpnssh -oBatchMode=yes -oNoneEnabled=yes -oNoneSwitch=yes "$@"' 0

commands:
    - before: repository
      run:
        - /etc/borgmatic/scripts/wakeup_server.sh {server_ip} {server_mac}

    - before: action
      when: [backup]
      run:
        - /etc/borgmatic/scripts/hooks.sh cleanup
        - /etc/borgmatic/scripts/hooks.sh before

    - after: action
      when: [backup]
      states: [finish]
      run:
        - /etc/borgmatic/scripts/hooks.sh after

    - after: action
      when: [backup]
      run:
        - /etc/borgmatic/scripts/hooks.sh cleanup

healthchecks:
    ping_url: "{healthchecks_ping_url}"
